---
name: CI
on:
  push:
    branches: 
      - main
      - dev

env:
  RELEASE_TYPE: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      
      - uses: actions/checkout@v3

      - name: Set the release folder
        run: |
          if [[ "${{github.base_ref}}" == "dev" || "${{github.ref}}" == "refs/heads/dev" ]]; then
            echo "RELEASE_TYPE=beta" >> $GITHUB_ENV
          fi

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: tar
          filename: config.tar.gz
          directory: .
          path: .
          exclusions: '*.git*'

      - name: Create Artifacts Directory
        run: |
          mkdir -p artifacts
          mv config.tar.gz artifacts/

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Copy files to the test website with the AWS CLI
        run: |
          cd artifacts
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }}/$RELEASE_TYPE